### ISSUE TITLE
Problem with sample code 

### ISSUE THREAD

**Issue by sashagaz** [NMGRL/toupcam#5]
I am getting the error below when running the sample code:

  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

Here is my system description:
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

**Comment by jirhiker** [comment]
does not appear to be related to the toupcam code. Are python and ctypes properly installed in your environment?

**Comment by sashagaz** [comment]
Yes I am using Python version 3.7.3 and ctypes version '1.1.0'. any tips or ideas would be much appreciated.

**Comment by jirhiker** [comment]
can you send more of the error trace?

Maybe try python 2.7

**Comment by sashagaz** [comment]
Here is the python version:
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

below is the full error-trace:
Traceback (most recent call last):
  File "capture_loop.py", line 18, in <module>
    from camera import ToupCamCamera
  File "C:\Users\agazman\Downloads\toupcam-master\toupcam-master\camera.py", line 26, in <module>
    from core import lib, TOUPCAM_EVENT_IMAGE, TOUPCAM_EVENT_STILLIMAGE, success, HToupCam
  File "C:\Users\agazman\Downloads\toupcam-master\toupcam-master\core.py", line 43, in <module>
    lib = ctypes.windll.LoadLibrary(os.path.join(root, directory, name))
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

Do you think that its an issue with the Python version?

**Comment by jirhiker** [comment]
try downloading the updated dll from #3 
move the downloaded toupcam.dll to toupcam/x86

**Comment by jirhiker** [comment]
i just updated the dll in the x86 directory. Pull the lastest commit and see if that works

**Comment by sashagaz** [comment]
Hey Jake, thanks for the help. I tried the new dll file and I am getting the same error:
OSError: [WinError 193] %1 is not a valid Win32 application

The code fails in line 43 of the the core.py file:
lib = ctypes.windll.LoadLibrary(os.path.join(root, directory, name))

**Comment by jirhiker** [comment]
don't know. I didn't make that dll. I only run linux and osx.  That dll was provided by #3
