### ISSUE TITLE
AWB issue

### ISSUE THREAD

**Issue by ltp7** [NMGRL/toupcam#7]
Hi,

I have a problem when trying to execute the do_awb() function. Python 3 gives me the following error:
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/media/luca/70B60ED66D483C58/travail_luca/Pollen_Reader/code/controle/controle_python/camera.py", line 216, in temptint_cb
    callback((temp, tint))
TypeError: function name must be string, bytes object or integer

Can you please help ? Thanks in advance,

ltp7

**Comment by jirhiker** [comment]
try changing do_awb in camera.py to 

```
    def do_awb(self, callback=None):
        """
        Toupcam_AwbOnePush(HToupCam h, PITOUPCAM_TEMPTINT_CALLBACK fnTTProc, void* pTTCtx);
        :return:
        """

        def temptint_cb(temp, tint):
            if callback:
                callback((temp, tint))

        self._temptint_cb = ctypes.CFUNCTYPE(None, ctypes.c_uint, ctypes.c_void_p)(temptint_cb)

        return self._lib_func('AwbOnePush', self._temptint_cb)
```

**Comment by ltp7** [comment]
Thanks for your help. The code now works without error, however the image taken using python code with do_awb() still has different color than the one taken imageusing Touplite (see touplite_awb.jpg and python_awb.jpg attached).

I also tried to manually set the temperature and tint using the values Touplite found for AWB (8458, 1299 in my case) which resulted in the image python_mwb.jpg, which has the same colors as python_awb.jpg, that is, more reddish than touplite_awb.jpg. I suspect the values (8458, 1299), while being both displayed in Touplite as the values used for doing AWB, and being used by do_awb() in camera.py, do not correspond to the actual values used by Touplite... Or maybe they are, but toupcam's python implementation of AWB does not work with the same temperature and tint values as Touplite.

Any thoughts ? Thanks in advance
![python_awb](https://user-images.githubusercontent.com/41062994/77738729-a3e98800-7010-11ea-91f9-80cf89a90524.jpg)
![python_mwb](https://user-images.githubusercontent.com/41062994/77738734-a4821e80-7010-11ea-80bb-79e21107d044.jpg)
![touplite_awb](https://user-images.githubusercontent.com/41062994/77738737-a5b34b80-7010-11ea-9644-07fd3fda3400.jpg)

**Comment by ltp7** [comment]
Update: I've added a time.(3) after calling do_awb() in my code, and now it seems the background color is quite satisfying:

Python AWB:

![python_awb](https://user-images.githubusercontent.com/41062994/77743517-7dc7e600-7018-11ea-8f34-84cf43262dbb.jpg)

Touplite AWB:

![touplite_awb](https://user-images.githubusercontent.com/41062994/77743538-88827b00-7018-11ea-9c7a-dc87ec218327.jpg)

**Comment by jirhiker** [comment]
you can try the following to print the calculated temp and tint then take a picture
```python
cam = ToupCamCamera(cid=...)
    if cam.open():
        time.sleep(1)
        cam.save('no_awb.jpg')

        def awb_hook(te, ti):
            print('temp={}, tint={}'.format(te, ti))
            cam.save('via_hook_awb.jpg')

        cam.do_awb(callback=awb_hook)

        # pic saved by `awb_hook` or here manually
        #time.sleep(1)
        #cam.save('awb.jpg')
```
