### ISSUE TITLE
camera error

### ISSUE THREAD

**Issue by areebakq** [NMGRL/toupcam#9]
Hi, I keep getting the following error when trying to run camera.py:

Traceback (most recent call last):
  File "c:\Users\akq190000\Downloads\toupcam-20210804T155303Z-001\toupcam\camera.py", line 279, in <module>
    cam.save('foo.jpg')
  File "c:\Users\akq190000\Downloads\toupcam-20210804T155303Z-001\toupcam\camera.py", line 55, in save
    image = self.get_pil_image()
  File "c:\Users\akq190000\Downloads\toupcam-20210804T155303Z-001\toupcam\camera.py", line 82, in get_pil_image
    raw = data.view(uint8).reshape(data.shape + (-1,))
AttributeError: 'NoneType' object has no attribute 'view'

I have 2 cameras connected to my computer that work fine with other code and I'm not sure where this error is coming from. I am sort of a beginner in Python so apologies if it's an obvious thing I missed. Any help is appreciated!

**Comment by milkyyyyyyyy** [comment]
Hi there! HAS ANYONE solved this problem? I have just the same trouble.
Think just than toupcam are rudimentary for modern development of software solutions for digital microscopes.
